/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sis.gui.runtime;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import sis.gui.model.SectionModel;

public class SIS extends Application {
    SectionModel sectionModel = new SectionModel();

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) {
        stage.setTitle("Course Registration");

        try {
            var scene = new Scene(FXMLLoader.load(
                    SIS.class.getResource("../view/login-screen-view.fxml")),
                    1280, 720);
            stage.setScene(scene);
            stage.show();
        } catch (Exception e) {
            System.err.println(e);
            System.out.println(SIS.class.getResource("../view/login-screen-view.fxml"));
        }

    }
}
