/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sis.gui.runtime;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import sis.gui.model.SectionModel;

public class SIS extends Application {
    SectionModel sectionModel = new SectionModel();

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) {
        stage.setTitle("Course Registration");
        stage.setScene(new Scene(new VBox(), 400.0, 300.0));
        stage.show();
    }
}
